steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/gcp-devops/gcp-devops-image:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/gcp-devops/gcp-devops-image:latest']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --image=gcr.io/$PROJECT_ID/gcp-devops-image
  - --location=us-central1-c	
  - --cluster=gcp-devops-cluster
  - --namespace=gcp-devops-prod
options:
  logging: CLOUD_LOGGING_ONLY
 
