steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-devops-444500/gcp-devops-01/my-image:v1.0', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gcp-devops-444500/gcp-devops-01/my-image:v1.0']
    
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   entrypoint: 'bash'
  #   args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']

  # To deploy on cloud functions
  # - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  #   args:
  #     - gcloud
  #     - functions
  #     - deploy
  #     - test_function
  #     - --region=us-central1
  #     - --source=.
  #     - --trigger-http
  #     - --runtime=python312

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: 
      - 'run'
      - 'deploy'
      - 'gcp-app-deploy'
      - 'us-central1-docker.pkg.dev/gcp-devops-444500/gcp-devops-01/my-image:v1.0'
      - 'LOCATION-us-central1-docker.pkg.dev/gcp-devops-444500/gcp-devops-01/my-image:v1.0'
      - 'us-central1'
      - 'us-central1'
images:
- 'LOCATION-us-central1-docker.pkg.dev/gcp-devops-444500/gcp-devops-01/my-image:v1.0'

timeout: '1600s'


options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: cicd-devops@gcp-devops-444500.iam.gserviceaccount.com
