steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-devops-444500/gcp-devops-01/my-image:v1.0', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gcp-devops-444500/gcp-devops-01/my-image:v1.0']
    
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
#timeout: '1600s'


options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: gcp-devops-444500@appspot.gserviceaccount.com


