steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-devops-444500/gcp-devops-01/my-image:v1.0', '.']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gcp-devops-444500/gcp-devops-01/my-image:v1.0']
    
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-service'
      - '--image=us-central1-docker.pkg.dev/gcp-devops-444500/gcp-devops-01/my-image:v1.0'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'


options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: gcp-devops-444500@appspot.gserviceaccount.com


